### ISSUE TITLE
Demo does not work using Safari 

### ISSUE THREAD

**Issue by tscholze** [limefrogyank/BlazorFabric#24]
First of all, thank you for your great work to leverage the React work of the Fabric team to be useable in a Blazor context. Great!

Secondly, I noticed that the demo at https://blazorfabric.azurewebsites.net works great on macOS using Chrome-based Browsers like Chrome or Microsoft Edge but not in Safari. Is this just a behavior of the moment or is no support, also in long term, not planned to support Safari?

**Error message:**
![Bildschirmfoto 2019-10-30 um 09 30 20](https://user-images.githubusercontent.com/5583469/67841248-ef4a4980-faf7-11e9-9b03-9ad825003532.png)

**Date of test:**
30th Oct. 2019

**macOS:** 
10.14.6 (18G95)

**Safari:** 
Version 13.0.1 (14608.2.11.1.11)

**Comment by limefrogyank** [comment]
I have not tried safari so I didn't know this.  Does safari have webassembly enabled automatically?  Whatever the case, I should get this demo to work using server side blazor, too.

Sent from my Windows 10 device

**Comment by limefrogyank** [comment]
This is either a Safari bug or a general client-size Blazor bug... 

See end of thread:
https://github.com/aspnet/AspNetCore/issues/16180

Here's the bug report:
http://www.openradar.me/50400451

These controls should work in a server-side project just fine on Safari since no webassembly is used.  But I haven't tested them in a while on server-side to be sure.  For client-side, there's nothing I can do at the moment.

**Comment by tscholze** [comment]
@limefrogyank thanks for your investigation! If you want you can close this issue because it's not your fault. :)
