### ISSUE TITLE
StackTokens-Properties not work

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#47]
I think StackTokens-Properties like Max-Width or Max-Heigh now not working because the values don't have unit's.
I think there are two ways to solve this problem:

1. values become strings instead of double
2. all values get unit 'px' or '%'

**Comment by limefrogyank** [comment]
Ah, yes... I forgot to add the units under style.  

I wonder if we can use `CssValue` for it.  (see BaseComponent)  I copied this idea from someone else's attempt to port Fabric to Blazor.  

If we make MaxWidth a `CssValue` instead of a double (or string), the property in razor would be `MaxWidth.AsLength`.  This means if the `MaxWidth` is set with a double, then the `AsLength` property would automatically append a "px" to the string version.  If the property is set as a string instead, only that string is used.

**Comment by Eweol** [comment]
I will have a look to it this evening maybe I can find a good solution like this

**Comment by Eweol** [comment]
Works quiet fine with CssValue instead of double or string
